trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1
  limit_train_batches: 5
  limit_val_batches: 0
  logger: False
  enable_checkpointing: False

model:
  class_path: training.mask_classification_semantic.MaskClassificationSemantic
  init_args:
    attn_mask_annealing_enabled: True
    attn_mask_annealing_start_steps: [10, 20, 30]
    attn_mask_annealing_end_steps: [20, 30, 40]
    network:
      class_path: models.eomt.EoMT
      init_args:
        num_q: 100
        num_blocks: 1
        encoder:
          class_path: models.vit.ViT
          init_args:
            backbone_name: vit_base_patch16_224
            img_size: [224, 224]

data:
  class_path: datasets.cityscapes_semantic.CityscapesSemantic
  init_args:
    path: "cityscapes"
    batch_size: 2
    num_workers: 0
    img_size: [224, 224]
    num_classes: 19
    check_empty_targets: False
